# Generated by Django 6.0.4 on 2026-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_list", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["mark", "-datetime"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="mark",
            field=models.BooleanField(default=False),
        ),
    ]
